### CREATE A NEW TEAM
POST {{BASE_URL}}/teams/create
Content-Type: application/json

{
  "name": "team 1",
  "description": "",
  "team_lead": "Joshua Ogunwole",
  "team_member": ["Joshua Ogunwole", "Bolatito Ogunwole", "Hannah Ogunwole"],
  "created_by": "xp",
  "updated_by": "up"
}

### GET TEAMS
GET {{BASE_URL}}/teams/all?page=1&limit=50
Content-Type: application/json

### GET TEAM BY ID
GET {{BASE_URL}}/teams/67de0141ee7ad487b8861b73
Content-Type: application/json



### GET TEAM USING Name
GET {{BASE_URL}}/teams/te
Content-Type: application/json


### Archive team
PATCH {{BASE_URL}}/teams/archive
Content-Type: application/json

{
  "name": "name",
  "description": "",
  "team_lead": "1234",
  "team_member": ["member1","member2"],
  "created_by": "user1",
  "updated_by": "user1",
  "created_at": "",
  "updated_at": "",
  "archive_status": false,
  "is_deleted_status": false
}

### UnArchive team
PATCH {{BASE_URL}}/teams/unarchive
Content-Type: application/json

{
  "name": "name",
  "description": "",
  "team_lead": "1234",
  "team_member": ["member1","member2"],
  "created_by": "user1",
  "updated_by": "user1",
  "created_at": "",
  "updated_at": "",
  "archive_status": true,
  "is_deleted_status": false
}

### Add Member to a team
PATCH {{BASE_URL}}/teams/add-members
Content-Type: application/json

{
  "team_members": ["Anonmous member"],
  "team":{
    "_id": "67de0141ee7ad487b8861b73",
    "created_at": "2025-03-22T00:16:01.034Z",
    "updated_by": "up",
    "name": "team 1",
    "description": "",
    "team_lead": "Joshua Ogunwole",
    "created_by": "xp",
    "team_member": [
      "Joshua Ogunwole",
      "Bolatito Ogunwole",
      "Hannah Ogunwole"
    ],
    "archive_status": false,
    "is_deleted_status": false,
    "updated_at": "2025-03-22T00:16:01.034Z"
  }
}

### Remove Members from a team
PATCH {{BASE_URL}}/teams/remove-members
Content-Type: application/json

{
  "team_members": ["member1","member2"],
  "team":{
    "name": "",
    "description": "",
    "team_lead": "yuu",
    "team_member": ["user1","user2"],
    "created_by": "",
    "updated_by": "user_by",
    "created_at": "",
    "updated_at": "",
    "archive_status": false,
    "is_deleted_status": false
  }
}

### Push to bin
PATCH {{BASE_URL}}/teams/bin
Content-Type: application/json

{
  "name": "",
  "description": "",
  "team_lead": "",
  "team_member": ["user1","user2"],
  "created_by": "",
  "updated_by": "",
  "created_at": "",
  "updated_at": "",
  "archive_status": false,
  "is_deleted_status": false
}

### Restore from bin
PATCH {{BASE_URL}}/teams/restore
Content-Type: application/json

{
  "name": "",
  "description": "",
  "team_lead": "",
  "team_member": ["user1","user2"],
  "created_by": "",
  "updated_by": "user_by",
  "created_at": "",
  "updated_at": "",
  "archive_status": false,
  "is_deleted_status": true
}

### Change team lead
PATCH {{BASE_URL}}/teams/change-lead
Content-Type: application/json

{
  "lead": "new_lead",
  "team": {
    "name": "",
    "description": "",
    "team_lead": "user1",
    "team_member": ["user1","user2"],
    "created_by": "",
    "updated_by": "user_new",
    "created_at": "",
    "updated_at": "",
    "archive_status": false,
    "is_deleted_status": false
  }
}

### Delete team
DELETE {{BASE_URL}}/teams/delete
Content-Type: application/json

{
  "name": "",
  "description": "",
  "team_lead": "",
  "team_member": "",
  "created_by": "",
  "updated_by": "",
  "created_at": "",
  "updated_at": "",
  "archive_status": false,
  "is_deleted_status": false
}

